name: hour-email-report

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # every five minute
    - cron:  '0 */1 * * *'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Print log
      run: |
        echo this report at each hour
        echo -n hour report at  >> github-action.log
        date >> github-action.log
        date
    - name: Send mail
      uses: dawidd6/action-send-mail@master
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Hour report - Github Actions job result
        # Literal body:
        body: Another hour has just past.
        # Read file contents as body:
        # body: file://README.md
        to: 240155787@qq.com
        from: ProgressBar20XX
        # Optional content type:
        content_type: text/html
      
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Add changes by Action" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
