name: auto-email

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Bash Script to create content
      run: |
        echo "Dear XXX,<br>" > content.html
        echo >> content.html
        echo Welcome to join my email list. >>content.html
        echo >> content.html
        echo "check out the parameter: $0 , $1" >>content.html

        echo >> content.html
        echo from >> content.html
        echo >> content.html
        echo ProgressBar20XX >> content.html
        echo >> content.html
        date >> content.html
        ls >> content.html
      #uses: lafernando/github-action-bash/@master
      #with:
      #  script: email/create-content.sh

    - uses: actions/upload-artifact@v1
      with:
        name: logfile
        path: content.html

    - uses: actions/checkout@v2

    - name: Send mail
      uses: dawidd6/action-send-mail@master
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: auto email - Github Actions job result
        # Literal body:
        # body: You got this email at every push. Build job of ${{github.repository}} completed successfully!
        # Read file contents as body:
        # body: file://email/content.html
        body: file://content.html
        to: 240155787@qq.com,weilei.zeng@foxmail.com
        from: ProgressBar20XX
        # Optional content type:
        content_type: text/html
